[package]
name = "providers"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "providers"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
event-bus = { path = "../event-bus" }
futures-core = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true }
wiremock = { workspace = true }
