[package]
name = "mock-openai"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "mock_openai"

[dependencies]
serde_json = { workspace = true }

[dev-dependencies]
event-bus = { path = "../event-bus" }
futures-util = { workspace = true }
providers = { path = "../providers" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
