//! Base context inspection: the system text, tools and model settings a run starts with.
//!
//! [`compose_system_sections`] is the single source of the initial system message:
//! the agent loop joins its sections into the provider request, and
//! [`crate::AgentRuntime::preview_base_context`] returns the same sections with their
//! provenance, so the inspector never drifts from what runs actually receive.

mod preview;
mod run_view;

use std::path::{Path, PathBuf};

use agents::Role;
use serde::{Deserialize, Serialize};

use crate::agent_loop::LoopShared;
use crate::compaction::policy::compaction_policy_text;
use crate::prompt::{PromptPartKind, SystemPromptCatalogError, classify};
use crate::rules;
use crate::skill::{SkillLoadError, render_skills_section};

pub use preview::{BaseContextReport, BaseContextRequest};
pub use run_view::RunContextView;

const BYTES_PER_TOKEN: u64 = 4;
const WORKSPACE_NOTE_PREFIX: &str = "Current workspace (evorch): ";

/// Bytes / 4, matching the compaction estimator's heuristic.
pub fn estimate_text_tokens(text: &str) -> u64 {
    u64::try_from(text.len())
        .unwrap_or(u64::MAX)
        .div_ceil(BYTES_PER_TOKEN)
}

/// The workspace note appended to the system message once the active root is known.
pub(crate) fn workspace_note(root: &Path) -> String {
    format!("{WORKSPACE_NOTE_PREFIX}{}.", root.display())
}

/// Whether a system text block is the workspace note written by [`workspace_note`].
pub(crate) fn is_workspace_note(text: &str) -> bool {
    text.starts_with(WORKSPACE_NOTE_PREFIX)
}

/// Kinds of base context sections, in the order the system message joins them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ContextSectionKind {
    RoleBaseline,
    ModelFamily,
    CategoryOverlay,
    IntentGate,
    Appendix,
    Skills,
    Rules,
    CompactionPolicy,
    Workspace,
    /// Validated lessons appended to the first user message, not the system message.
    Memory,
}

impl ContextSectionKind {
    /// Short label for UI rows.
    pub const fn label(self) -> &'static str {
        match self {
            Self::RoleBaseline => "Role baseline",
            Self::ModelFamily => "Model family",
            Self::CategoryOverlay => "Category overlay",
            Self::IntentGate => "Intent gate",
            Self::Appendix => "Preset appendix",
            Self::Skills => "Skills",
            Self::Rules => "Rules",
            Self::CompactionPolicy => "Compaction policy",
            Self::Workspace => "Workspace",
            Self::Memory => "Memory lessons",
        }
    }

    /// Whether this section is part of the system message.
    pub const fn in_system_message(self) -> bool {
        !matches!(self, Self::Memory)
    }
}

impl From<PromptPartKind> for ContextSectionKind {
    fn from(kind: PromptPartKind) -> Self {
        match kind {
            PromptPartKind::RoleBaseline => Self::RoleBaseline,
            PromptPartKind::ModelFamily => Self::ModelFamily,
            PromptPartKind::CategoryOverlay => Self::CategoryOverlay,
            PromptPartKind::IntentGate => Self::IntentGate,
            PromptPartKind::Appendix => Self::Appendix,
        }
    }
}

/// Where a section's text comes from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContextSource {
    /// A preset whose layer has not been resolved (only during a real run).
    Preset { name: String },
    /// A preset compiled into the binary.
    BundledPreset { name: String },
    /// A user override at `<user config dir>/presets/<name>.md`.
    UserPreset { name: String, path: PathBuf },
    /// Files read from disk (rules, skill bodies).
    Files { paths: Vec<PathBuf> },
    /// Text generated by the runtime.
    Generated,
}

/// One labelled piece of base context.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContextSection {
    pub kind: ContextSectionKind,
    pub source: ContextSource,
    pub text: String,
    pub estimated_tokens: u64,
}

impl ContextSection {
    fn new(kind: ContextSectionKind, source: ContextSource, text: String) -> Self {
        Self {
            kind,
            source,
            estimated_tokens: estimate_text_tokens(&text),
            text,
        }
    }
}

/// A tool definition the model would see.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextTool {
    pub name: String,
    pub description: String,
    pub input_schema: serde_json::Value,
    pub estimated_tokens: u64,
}

/// Something a reader might expect in the context that is not there, with the reason.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContextExclusion {
    pub item: String,
    pub reason: String,
}

/// Initial system prompt composition failures (issue #53 / AC6).
///
/// Display carries identifiers only, never skill bodies or frontmatter values
/// (same contract as [`SystemPromptCatalogError`] / [`SkillLoadError`]).
#[derive(Debug, thiserror::Error)]
pub(crate) enum InitialSystemPromptError {
    #[error(transparent)]
    Catalog(#[from] SystemPromptCatalogError),
    #[error(transparent)]
    Skills(#[from] SkillLoadError),
    /// load_skills was given but no skill registry is connected.
    #[error("skill registry is not configured")]
    SkillsNotConfigured,
}

/// Inputs to [`compose_system_sections`] that vary per run.
pub(crate) struct SystemInputs<'a> {
    pub(crate) role: Role,
    pub(crate) category: Option<&'a str>,
    pub(crate) load_skills: &'a [String],
    /// First user message length, counted against the rules injection budget.
    pub(crate) prompt_len: usize,
    pub(crate) active_root: Option<&'a Path>,
}

/// Resolve the initial system message as ordered sections: catalog, skills, rules, compaction.
///
/// Joining the non-empty sections with one blank line gives the exact system text.
pub(crate) fn compose_system_sections(
    shared: &LoopShared,
    inputs: &SystemInputs<'_>,
) -> Result<Vec<ContextSection>, InitialSystemPromptError> {
    let model_id = shared.model.selected_model(inputs.role, inputs.category);
    let mut sections = Vec::new();
    if let Some(catalog) = shared.system_prompts.as_ref() {
        for part in catalog.system_prompt_sections_for(inputs.role, inputs.category, &model_id)? {
            let source =
                part.preset
                    .map_or(ContextSource::Generated, |name| ContextSource::Preset {
                        name,
                    });
            sections.push(ContextSection::new(part.kind.into(), source, part.text));
        }
    }
    // The rules budget counts the joined catalog text, separators included.
    let catalog_bytes = join_system_sections(&sections).len();
    if let Some(skills) = resolve_skills_section(shared, inputs.load_skills)? {
        sections.push(skills);
    }
    let compaction = shared
        .compaction_configured
        .then(|| compaction_policy_text(&shared.compaction, classify(&model_id)));
    let estimated_history_bytes = u64::try_from(
        catalog_bytes
            + sections
                .iter()
                .filter(|section| section.kind == ContextSectionKind::Skills)
                .map(|section| section.text.len())
                .sum::<usize>()
            + compaction.as_ref().map_or(0, String::len)
            + inputs.prompt_len,
    )
    .unwrap_or(u64::MAX);
    if let Some(source) = shared.rules.as_ref()
        && let Some(text) =
            rules::startup_snapshot(source, inputs.active_root, None, estimated_history_bytes)
    {
        let paths = rules::startup_rule_files(source, inputs.active_root)
            .into_iter()
            .filter(|file| file.excluded.is_none())
            .map(|file| file.path)
            .collect();
        sections.push(ContextSection::new(
            ContextSectionKind::Rules,
            ContextSource::Files { paths },
            text,
        ));
    }
    if let Some(text) = compaction {
        sections.push(ContextSection::new(
            ContextSectionKind::CompactionPolicy,
            ContextSource::Generated,
            text,
        ));
    }
    sections.retain(|section| !section.text.is_empty());
    Ok(sections)
}

/// Join system sections exactly as the initial system message does.
pub(crate) fn join_system_sections(sections: &[ContextSection]) -> String {
    sections
        .iter()
        .filter(|section| section.kind.in_system_message())
        .map(|section| section.text.as_str())
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn resolve_skills_section(
    shared: &LoopShared,
    load_skills: &[String],
) -> Result<Option<ContextSection>, InitialSystemPromptError> {
    if load_skills.is_empty() {
        return Ok(None);
    }
    let Some(registry) = shared.skills.as_ref() else {
        return Err(InitialSystemPromptError::SkillsNotConfigured);
    };
    let mut loaded = Vec::with_capacity(load_skills.len());
    let mut paths = Vec::new();
    for name in load_skills {
        loaded.push((name.clone(), registry.load_body(name)?));
        if let Some(crate::skill::SkillSource::Filesystem { dir }) =
            registry.get(name).map(|entry| &entry.source)
        {
            paths.push(dir.join("SKILL.md"));
        }
    }
    let source = if paths.is_empty() {
        ContextSource::Generated
    } else {
        ContextSource::Files { paths }
    };
    Ok(Some(ContextSection::new(
        ContextSectionKind::Skills,
        source,
        render_skills_section(&loaded),
    )))
}

/// Resolve which preset layer each [`ContextSource::Preset`] section was read from.
pub(crate) fn resolve_preset_origins(
    sections: &mut [ContextSection],
    user_config_dir: Option<&Path>,
) {
    let presets_dir = user_config_dir.map(|dir| dir.join("presets"));
    for section in sections {
        let ContextSource::Preset { name } = &section.source else {
            continue;
        };
        section.source = match config::PresetStore::origin(name, presets_dir.as_deref()) {
            Some(config::PresetOrigin::User(path)) => ContextSource::UserPreset {
                name: name.clone(),
                path,
            },
            Some(config::PresetOrigin::Bundled) | None => {
                ContextSource::BundledPreset { name: name.clone() }
            }
        };
    }
}
