[package]
name = "event-bus"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "event_bus"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
tracing-subscriber = { workspace = true }
